I took the following courses:

1. "Learn Reactive Programming with Spring Framework 5" by John Thompson.
2. "Reactive Programming in Modern Java using Project Reactor
" by Pragmatic Code School.
3. "Reactive Spring Boot, 3d Edition" by Josh Long.
4. "DevOps for Absolute Beginners: Azure DevOps, Docker, Kubernetes, Jenkins, Terraform, Ansible - AWS, Azure & Google Cloud" by in28Minutes.
5. "GCP ACE - Google Cloud Associate Cloud Engineer certification. Begin your Google Cloud Platform - GCP journey!" by in28Minutes.
6. "Build highly scalable and resilient Microservices with Spring WebFlux / Reactive Stack" by Vinoth Selvaraj.

== Build Docker Image with Dockerfile

1. Package: mvn package
2. Build Docker image
   docker build -t springio/spring-webflux-docker-api:1.0.0 .
3. Run
   docker run -it -p8081:8080 springio/spring-webflux-docker-api:1.0.0

== Build Docker Image with Sprint Boot Plugin

This does not need a Dockerfile, which will be ignored if it exists.

   mvn spring-boot:build-image -Dspring-boot.build-image.imageName=springio/spring-webflux-docker-api:1.0.0

== Build Docker Image with Google Jib
1. Build the Docker image locally
   mvn compile jib:dockerBuild
2. Build and push to Registry
   mvn compile jib:build
3. Using lifecycle
   mvn package
   
**Using Spring Profiles**

docker run -e "SPRING_PROFILES_ACTIVE=prod" -p 8080:8080 spring-webflux-docker-api:1.0.0

**Debug Application Running inside Contaner**

docker run -e "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n" -p 8080:8080 -p 5005:5005 spring-webflux-docker-api:1.0.0

== Set up Docker Containers to Run the Application
The simplest way to start both Postgres and Mongodb:

```
$ cd coontainer
$ docker-compose up
```

. Create a Docker network
  docker network create webflux_net
. Start Mongodb
```
  docker run \
  -p27017:27017 \
  --name=mongoserver \
  --rm \
  --network=webflux_net mongo
```
. Run the application
.. Either run it in local host directly because the application connects to localhost:27017.
```
.. Run it in container
  docker run \
  --name webfluxapi \
  --rm --network=webflux_net \
  -p8080:8080 \
  -e MONGO_URL=mongodb://mongoserver:27017/dev \
  spring-webflux-docker-api:1.0.1
```
here, --rm means automatic cleaning up the container and remove the file system after the conteiner exits.

