# Application logging
logging:
  charset:
    console: utf-8
  level:
    root: INFO
    org:
      springframework=INFO: INFO

spring:
  main:
    banner-mode: console
  profiles:
    active: dev

---
# Profile "dev"

spring:
  profiles:
    include: dev
  r2dbc:
    url: r2dbc:postgresql://postgres:postgres@localhost:5432/postgres
    initialization-mode: alawys
  sql:
    init:
      data-locations: classpath*:db/postgres/data.sql
      schema-locations: classpath*:db/postgres/schema.sql
  data:
    mongodb:
      uri: mongodb://localhost:27017/dev
server:
  port: 8080
# The following is to enable SSL for the server
#  port: 8443
#  ssl:
#    enabled: true
#    key-alias: myalias
#    key-store: classpath:myidentity.jks
#    key-store-type: jks
#    key-store-password: mypassword
#    key-password: mypassword
#    trust-store:
#    trust-store-type:
#    trust-store-password:

---
# Profile "prod"
