###
GET http://localhost:8080/api/health

###
GET http://localhost:8080/api

###
GET http://localhost:8080/api/hello

###
GET http://localhost:8080/api/hello/Jack

###
# Using HelloHandlerFilter to return FORBIDDEN
GET http://localhost:8080/api/hello/wy

###
GET http://localhost:8080/books/init

###
GET http://localhost:8080/books

###
GET http://localhost:8080/some/pathVariable/others?id=queryVar

###
GET http://localhost:8080/ca/relationship

###
GET http://localhost:8080/ca/permission

###
GET http://localhost:8080/ca/account
Accept: application/json

###
# /api/{profileId}
# profileId = 1,2,3,...
GET http://localhost:8080/ca/ca/3
Accept: application/json

###
# Stock Quote Streaming
GET http://localhost:8080/quotes
Accept: application/x-ndjson

###
# Stream Fibonacci number
GET http://localhost:8080/api/fib
Accept: text/event-stream

###
# Handling exception
GET http://localhost:8080/api/exceptionHandling

###
# Handling exception
GET http://localhost:8080/api/globalExceptionHandling

###
# RequestPredicates
GET http://localhost:8080/api/pathPredicate/1
Accept: application/json

