###
GET http://localhost:8080/

###
GET http://localhost:8080/hello

###
GET http://localhost:8080/hello/Jack

###
GET http://localhost:8080/books/init

###
GET http://localhost:8080/books

###
GET http://localhost:8080/some/pathvariable1234/others?id=wy8162

###
GET http://localhost:8080/api/relationship

###
GET http://localhost:8080/api/permission

###
GET http://localhost:8080/api/account
Accept: application/json

###
# /api/{profileId}
# profileId = 1,2,3,...
GET http://localhost:8080/api/ca/3
Accept: application/json

###
# Stock Quote Streaming
GET http://localhost:8080/quotes
Accept: application/x-ndjson

###
# Stream Fibonacci number
GET http://localhost:8080/api/fib
Accept: text/event-stream

###
# Handling exception
GET http://localhost:8080/api/exceptionHandling

###
# Handling exception
GET http://localhost:8080/api/globalExceptionHandling